-- Migration: Add MFA fields to users table
-- This file shows the SQL that will be generated by Prisma
-- You don't need to run this manually - use: npx prisma migrate dev --name add_mfa_fields

-- Add MFA fields to users table
ALTER TABLE "users" ADD COLUMN "mfaEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN "mfaSecret" TEXT;
ALTER TABLE "users" ADD COLUMN "mfaBackupCodes" TEXT;
ALTER TABLE "users" ADD COLUMN "lastLogin" TIMESTAMP(3);

-- Note: Prisma will handle this automatically when you run:
-- npx prisma migrate dev --name add_mfa_fields
